disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Siam's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

  [params.author]
  name = "Table Lamp Writer"
  image = "logo.png"
  headline = "Books, Computers, Physics, Productivity, Life and Everything in Between"
  bio = "A little bit about me"

    [[params.author.links]]
    instagram = "https://www.instagram.com/siam.rahman.29/"

["params.author"]
name = "Siam Rahman"
image = "ChatGPT Image May 9, 2025, 07_39_07 PM.png"
headline = "Scio me nihil scire"
