[[main]]
name = "All Writings"
pageRef = "posts"
weight = 1

[[main]]
name = "About"
pageRef = "about"
weight = 2
url = "about"

[[main]]
pre = "github"
url = "https://github.com/SiamRahman29"
identifier = "G1MpmiNmqY"
weight = 9_999

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/siamrahman-29/"
identifier = "LCAUVb7Oto"
weight = 9_999

[[footer]]
none = "none"
